import { useEffect, useState } from 'react'
import { NavLink, Navigate, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom'
import { customers as adminCustomers, notifications as adminNotifications, reviews as adminReviews, stats } from '../data/adminMockData'
import { allServices } from '../data/services'
import { getAdminBookings, getAdminDashboard, getAdminNotifications, getServices, markAllNotificationsRead, markNotificationRead, updateAdminBookingStatus } from '../services/api'
import AdminLogout from '../components/common/AdminLogout'
import './AdminApp.css'

const nav = [['Dashboard', '/admin', 'ri-dashboard-line'], ['Bookings', '/admin/bookings', 'ri-calendar-check-line'], ['Services', '/admin/services', 'ri-grid-line'], ['Customers', '/admin/customers', 'ri-group-line'], ['Notifications', '/admin/notifications', 'ri-notification-3-line'], ['Reviews', '/admin/reviews', 'ri-star-line'], ['Settings', '/admin/settings', 'ri-settings-3-line']]
const adminBookings = []
const adminServices = allServices.map((service, index) => {
  const adminService = { ...service, name: service.serviceName, bookings: [86, 48, 38, 32, 28, 16][index] || 8, active: true }
  return adminService
})
const statusClass = (value) => value.toLowerCase().replaceAll(' ', '-')

function Sidebar({ open, onClose }) {
  return <aside className={`admin-sidebar ${open ? 'is-open' : ''}`}><div className="admin-brand"><img src="/take-wind-logo.png" alt="" /><span><strong>Take <em>Wind</em></strong><small>Admin workspace</small></span><button className="admin-icon mobile-close" onClick={onClose}>×</button></div><nav>{nav.map(([label, path, icon]) => <NavLink key={path} to={path} end={path === '/admin'} onClick={onClose} className={({ isActive }) => isActive ? 'active' : ''}><i className={icon} /><span>{label}</span>{label === 'Notifications' && <b>3</b>}</NavLink>)}</nav><div className="admin-sidebar-footer"><AdminLogout /><p>Created by <strong>Puspita</strong></p></div></aside>
}

function Header({ onMenu }) { const location = useLocation(); const current = nav.find((item) => item[1] === location.pathname)?.[0] || 'Booking details'; return <header className="admin-header"><button className="admin-icon menu-trigger" onClick={onMenu}><i className="ri-menu-line" /></button><div className="admin-breadcrumb"><span>Workspace</span><b>/</b><strong>{current}</strong></div><div className="admin-header-actions"><span className="admin-date"><i className="ri-calendar-line" /> Tuesday, 11 Aug 2026</span><button className="admin-icon notification-trigger"><i className="ri-notification-3-line" /><b /></button><div className="admin-profile"><span className="admin-avatar avatar-purple">PS</span><span><strong>Puspita S.</strong><small>Administrator</small></span><i className="ri-arrow-down-s-line" /></div></div></header> }
function Button({ children, primary, onClick }) { return <button className={`admin-button ${primary ? 'primary' : ''}`} onClick={onClick}>{children}</button> }
function Badge({ children }) { return <span className={`admin-badge ${statusClass(children)}`}>{children}</span> }
function Title({ eyebrow, title, description, children }) { return <div className="admin-title"><div><p>{eyebrow}</p><h1>{title}</h1><span>{description}</span></div>{children}</div> }
function Toast({ text, close }) { return <div className="admin-toast"><i className="ri-checkbox-circle-line" />{text}<button onClick={close}>×</button></div> }

function Dashboard({ viewBooking }) { const coreStats = stats.filter((item) => ['Total bookings', 'Pending bookings', 'Completed bookings', 'Total customers'].includes(item.label)); return <div className="admin-page"><Title eyebrow="Tuesday, 11 August 2026" title="Good morning, Puspita" description="Here is what is happening across your service business today." /><div className="admin-stats">{coreStats.map((item) => <article key={item.label}><span className={`stat-symbol ${item.tone}`}><i className={`ri-${item.icon === 'calendar' ? 'calendar' : item.icon === 'users' ? 'group' : item.icon === 'clock' ? 'time' : 'check'}-line`} /></span><div><small>{item.label.replace(' bookings', '')}</small><strong>{item.value}</strong></div></article>)}</div><section className="admin-panel admin-table-panel"><PanelHeading title="Recent bookings" subtitle="Latest activity from your customers"><NavLink to="/admin/bookings" className="admin-link">View all bookings ↗</NavLink></PanelHeading><BookingTable rows={adminBookings.slice(0, 5)} viewBooking={viewBooking} /></section><section className="admin-panel overview-panel simple-overview"><PanelHeading title="Bookings this week" subtitle="A quick view of your booking activity"><span className="chart-total">248 total bookings</span></PanelHeading><div className="fake-chart"><div className="chart-y"><span>60</span><span>40</span><span>20</span><span>0</span></div><svg viewBox="0 0 700 210" preserveAspectRatio="none" role="img" aria-label="Booking trend chart"><path d="M0 158 C55 128 76 146 112 118 S170 137 210 105 S268 125 310 92 S380 116 422 76 S474 100 520 61 S580 93 625 48 S667 63 700 25" fill="none" stroke="var(--primary)" strokeWidth="3" /></svg><div className="chart-x"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div></div></section></div> }

function PanelHeading({ title, subtitle, children }) { return <div className="admin-panel-heading"><div><h2>{title}</h2><p>{subtitle}</p></div>{children}</div> }
function BookingTable({ rows, viewBooking }) { return <div className="admin-table-scroll"><table><thead><tr><th>Booking ID</th><th>Customer</th><th>Service</th><th>Booking date</th><th>Location</th><th>Status</th><th>Update</th></tr></thead><tbody>{rows.length ? rows.map((item) => <tr key={item.id}><td><strong className="booking-id">{item.id}</strong></td><td><div className="admin-person"><span className="admin-avatar avatar-blue">{item.customer.split(' ').map((word) => word[0]).join('')}</span><span><strong>{item.customer}</strong><small>{item.phone}</small></span></div></td><td>{item.service}</td><td>{item.date}</td><td>{item.location}</td><td><Badge>{statusLabel(item.status)}</Badge></td><td><button className="admin-action" onClick={() => viewBooking(item)}>Update</button></td></tr>) : <tr><td colSpan="7" className="admin-empty">No bookings found.</td></tr>}</tbody></table></div> }

function BookingsPage({ viewBooking }) { const [search, setSearch] = useState(''); const [filter, setFilter] = useState('All statuses'); const rows = adminBookings.filter((item) => `${item.id} ${item.customer} ${item.service}`.toLowerCase().includes(search.toLowerCase()) && (filter === 'All statuses' || item.status === filter)); return <div className="admin-page"><Title eyebrow="Operations" title="Bookings" description="Stay on top of every service request from one place."><Button primary>＋ Create booking</Button></Title><div className="admin-filter admin-panel"><label><i className="ri-search-line" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search booking or customer..." /></label><select value={filter} onChange={(event) => setFilter(event.target.value)}><option>All statuses</option><option>Pending</option><option>Accepted</option><option>In Progress</option><option>Completed</option><option>Cancelled</option></select><select><option>All services</option>{adminServices.map((service) => <option key={service.name}>{service.name}</option>)}</select></div><section className="admin-panel admin-table-panel"><PanelHeading title={`All bookings · ${rows.length}`} subtitle="Manage and track your service appointments" /><BookingTable rows={rows} viewBooking={viewBooking} /><div className="admin-pagination">Showing 1-{rows.length} of 248 bookings <span>‹ &nbsp; <b>1</b> &nbsp; 2 &nbsp; 3 &nbsp; ›</span></div></section></div> }

function BookingDetails({ booking, toast }) { const navigate = useNavigate(); return <div className="admin-page"><button className="admin-back" onClick={() => navigate('/admin/bookings')}>← Back to bookings</button><Title eyebrow="Booking details" title={booking.id} description={`Created ${booking.created}`}><Badge>{booking.status}</Badge></Title><div className="admin-details-grid"><div><section className="admin-panel admin-detail-card"><h2>Customer information</h2><div className="admin-detail-values"><Detail label="Customer name" value={booking.customer} /><Detail label="Phone number" value={booking.phone} /><Detail label="Address" value={booking.location} /></div></section><section className="admin-panel admin-detail-card"><h2>Booking information</h2><div className="admin-detail-values"><Detail label="Booking ID" value={booking.id} /><Detail label="Service" value={booking.service} /><Detail label="Booking date" value={booking.date} /><Detail label="Expected completion" value="2.5 hours" /></div><div className="admin-note"><strong>Notes from customer</strong><p>Please call before arriving. This is a frontend-only booking detail view.</p></div></section><section className="admin-panel admin-detail-card"><h2>Service location</h2><div className="admin-map"><i className="ri-map-pin-2-line" /><strong>{booking.location}</strong><small>Map preview placeholder</small><Button onClick={() => toast('Google Maps will be connected later')}>Open in Google Maps ↗</Button></div></section></div><aside className="admin-panel admin-timeline"><h2>Booking timeline</h2>{['Booking Created', 'Booking Accepted', 'Service Started', 'Service Completed'].map((step, index) => <div className={index < 2 || booking.status === 'Completed' ? 'done' : ''} key={step}><b>{index < 2 || booking.status === 'Completed' ? '✓' : '○'}</b><span><strong>{step}</strong><small>{index === 0 ? booking.created : index < 2 ? 'Today, 09:36 AM' : 'Waiting for service'}</small></span></div>)}</aside></div></div> }
function Detail({ label, value }) { return <div><small>{label}</small><strong>{value}</strong></div> }

function ServicesPage({ toast }) { const [items, setItems] = useState(adminServices); return <div className="admin-page"><Title eyebrow="Catalogue" title="Services" description="Manage the services already available to customers."><Button primary onClick={() => toast('Add service form opened')}>＋ Add service</Button></Title><div className="admin-service-grid">{items.map((service) => <article className="admin-service-card" key={service.id}><div className="service-card-top"><span className="service-symbol">✦</span><button className="admin-icon" onClick={() => toast('Service actions opened')}>•••</button></div><h2>{service.name}</h2><p>{service.description}</p><div className="service-meta"><span><small>Category</small><strong>{service.categoryName}</strong></span><span><small>Bookings</small><strong>{service.bookings}</strong></span></div><footer><Badge>{service.active ? 'Active' : 'Paused'}</Badge><div><button className="admin-action" onClick={() => toast('Edit service opened')}>Edit</button><button className={`service-toggle ${service.active ? 'on' : ''}`} onClick={() => { setItems(items.map((item) => item.id === service.id ? { ...item, active: !item.active } : item)); toast('Service status updated') }}><i /></button></div></footer></article>)}</div></div> }

function CustomersPage({ toast }) { const [search, setSearch] = useState(''); const rows = adminCustomers.filter((item) => item.name.toLowerCase().includes(search.toLowerCase())); return <div className="admin-page"><Title eyebrow="Relationships" title="Customers" description="Understand your customers and their service history."><Button>↓ &nbsp; Export customers</Button></Title><div className="admin-filter admin-panel"><label><i className="ri-search-line" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search customers..." /></label></div><section className="admin-panel admin-table-panel"><PanelHeading title="Customer directory · 172 total" subtitle="Profiles and booking activity" /><div className="admin-table-scroll"><table><thead><tr><th>Customer</th><th>Phone</th><th>Total bookings</th><th>Completed</th><th>Last booking</th><th>Status</th><th /></tr></thead><tbody>{rows.map((item) => <tr key={item.name}><td><div className="admin-person"><span className="admin-avatar avatar-purple">{item.initials}</span><strong>{item.name}</strong></div></td><td>{item.phone}</td><td>{item.bookings}</td><td>{item.completed}</td><td>{item.last}</td><td><Badge>{item.active ? 'Active' : 'Inactive'}</Badge></td><td><button className="admin-action" onClick={() => toast(`${item.name}'s profile opened`)}>View</button></td></tr>)}</tbody></table></div></section></div> }

function NotificationsPage({ toast }) { const [items, setItems] = useState(adminNotifications); const unread = items.filter((item) => item.unread).length; const markAll = async () => { await markAllNotificationsRead(); setItems(items.map((item) => ({ ...item, unread: false }))); toast('All notifications marked as read') }; const markOne = async (id) => { await markNotificationRead(id); setItems(items.map((item) => item.id === id ? { ...item, unread: false } : item)); toast('Notification marked as read') }; return <div className="admin-page admin-narrow"><Title eyebrow="Inbox" title="Notifications" description="Stay updated on the activity that matters."><Button onClick={markAll}>✓ &nbsp; Mark all as read</Button></Title><div className="notification-summary"><i className="ri-notification-3-line" /><span><strong>{unread} unread notifications</strong><small>You are all caught up with your latest activity.</small></span></div><section className="admin-panel notification-list"><PanelHeading title="Recent activity" subtitle="Recent booking activity" />{items.map((item) => <article className={item.unread ? 'unread' : ''} key={item.id}><i className="ri-notification-3-line" /><span><strong>{item.title}</strong><p>{item.text}</p><small>{item.time}</small></span><button className="admin-action" onClick={() => markOne(item.id)}>Mark as read</button></article>)}</section></div> }

function ReviewsPage() { return <div className="admin-page"><Title eyebrow="Customer voice" title="Reviews" description="See what customers are saying about your services." /><section className="review-rating admin-panel"><small>Average Rating</small><strong>4.6 ★</strong></section><section className="admin-panel review-list"><PanelHeading title="Recent reviews" subtitle="Customer feedback from your latest bookings" />{adminReviews.map((review) => <article key={review.customer}><span className="admin-avatar avatar-orange">{review.customer.split(' ').map((word) => word[0]).join('')}</span><div><strong>{review.customer} <em>{'★'.repeat(review.rating)}</em></strong><small>{review.service} · {review.date}</small><p>{review.review}</p></div><button className="admin-action">View</button></article>)}</section></div> }

function SettingsPage() { return <div className="admin-page admin-narrow"><Title eyebrow="Workspace control" title="Settings" description="Configure the details for your business."><Button primary>Save changes</Button></Title><section className="admin-panel settings-card"><h2>Business information</h2><div className="settings-fields"><label>Business name<input defaultValue="Take Wind Services" /></label><label>Phone<input defaultValue="+91 98765 00000" /></label><label>Email<input defaultValue="hello@takewind.in" /></label><label>Address<input defaultValue="Bandra West, Mumbai" /></label></div></section><section className="admin-panel settings-card"><h2>Notification settings</h2><div className="settings-fields settings-toggles"><label>SMS<input type="checkbox" /></label><label>Email<input type="checkbox" defaultChecked /></label></div></section><section className="admin-panel settings-card"><h2>Admin profile</h2><div className="settings-fields"><label>Name<input defaultValue="Puspita Sharma" /></label><label>Email<input defaultValue="puspita@takewind.in" /></label></div></section></div> }

function AdminBookingDetailsRoute({ toast }) { const { bookingId } = useParams(); return <BookingDetails booking={adminBookings.find((item) => item.id === bookingId) || adminBookings[0]} toast={toast} /> }

const statusOptions = {
  pending: ['confirmed', 'cancelled'],
  confirmed: ['in_progress', 'completed', 'cancelled'],
  in_progress: ['completed'],
}
const statusLabel = (status) => ({ pending: 'Pending', confirmed: 'Confirmed', in_progress: 'In progress', completed: 'Completed', cancelled: 'Cancelled' }[status] || status)

function BookingUpdateModal({ booking, onClose, onUpdated, toast }) {
  const [nextStatus, setNextStatus] = useState(statusOptions[booking.status]?.[0] || '')
  const [saving, setSaving] = useState(false)
  const options = statusOptions[booking.status] || []
  const save = async () => {
    if (!nextStatus) return
    setSaving(true)
    try {
      const response = await updateAdminBookingStatus(booking.id, nextStatus.toLowerCase().replaceAll(' ', '_'))
      onUpdated(response.data.booking)
      toast(nextStatus === 'confirmed' ? 'Booking confirmed successfully. Customer has been notified.' : 'Booking status updated.')
      onClose()
    } catch (error) {
      toast(error.response?.data?.message || 'Unable to update this booking.')
    } finally { setSaving(false) }
  }
  return <div className="admin-modal-backdrop" onClick={onClose}><div className="admin-modal" onClick={(event) => event.stopPropagation()}><header><span><small>Update booking</small><h2>{booking.id}</h2></span><button onClick={onClose} aria-label="Close">×</button></header><div><div className="admin-person"><span className="admin-avatar avatar-blue">{booking.customer.split(' ').map((word) => word[0]).join('')}</span><span><strong>{booking.customer}</strong><small>{booking.phone}</small></span><Badge>{statusLabel(booking.status)}</Badge></div><div className="admin-detail-values"><Detail label="Service" value={booking.service} /><Detail label="Booking date" value={booking.date} /><Detail label="Location" value={booking.location} /><Detail label="Current status" value={statusLabel(booking.status)} /></div>{options.length ? <label className="admin-status-field">New status<select value={nextStatus} onChange={(event) => setNextStatus(event.target.value)}>{options.map((status) => <option key={status} value={status}>{statusLabel(status)}</option>)}</select></label> : <p className="admin-status-help">This booking has reached a final status and cannot be changed.</p>}</div><footer><Button onClick={onClose}>Cancel</Button>{options.length > 0 && <Button primary onClick={save}>{saving ? 'Saving…' : 'Save changes'}</Button>}</footer></div></div>
}

export default function AdminApp() {
  const [open, setOpen] = useState(false)
  const [selected, setSelected] = useState(null)
  const [toastText, setToastText] = useState('')
  const [, setVersion] = useState(0)
  useEffect(() => {
    getAdminBookings().then((response) => {
      const format = (value) => value ? new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium' }).format(new Date(value)) : '—'
      adminBookings.splice(0, adminBookings.length, ...response.data.bookings.map((booking) => ({ id: booking._id, customer: booking.customer?.name || booking.customer?.phone || 'Name unavailable', phone: booking.customer?.phone || '—', service: booking.service?.name || 'Service request', date: format(booking.date), location: booking.address, status: booking.status.replace('_', ' '), created: format(booking.createdAt) })))
      setVersion((value) => value + 1)
    }).catch((error) => setToastText(error.response?.data?.message || 'Unable to load bookings.'))
  }, [])
  useEffect(() => {
    Promise.all([getAdminDashboard(), getAdminBookings(), getAdminNotifications(), getServices()]).then(([dashboard, bookingResponse, notificationResponse, serviceResponse]) => {
      const format = (value) => value ? new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium' }).format(new Date(value)) : '—'
      stats.splice(0, stats.length, { label: 'Total bookings', value: String(dashboard.data.stats.totalBookings), tone: 'blue', icon: 'calendar' }, { label: 'Pending bookings', value: String(dashboard.data.stats.pendingBookings), tone: 'orange', icon: 'clock' }, { label: 'Completed bookings', value: String(dashboard.data.stats.completedBookings), tone: 'green', icon: 'check' }, { label: 'Total customers', value: String(dashboard.data.stats.totalCustomers), tone: 'purple', icon: 'users' })
      adminBookings.splice(0, adminBookings.length, ...bookingResponse.data.bookings.map((booking) => ({ id: booking._id, customer: booking.customer?.name || booking.customer?.phone || 'Name unavailable', phone: booking.customer?.phone || '—', service: booking.service?.name || 'Service request', date: format(booking.date), location: booking.address, status: booking.status.replace('_', ' '), created: format(booking.createdAt) })))
      adminNotifications.splice(0, adminNotifications.length, ...notificationResponse.data.notifications.map((notification) => ({ id: notification._id, title: notification.title, text: notification.message, time: format(notification.createdAt), unread: !notification.isRead })))
      adminServices.splice(0, adminServices.length, ...serviceResponse.data.services.map((service) => ({ id: service._id, name: service.name, description: service.description, categoryName: 'Service', bookings: 0, active: service.isActive })))
      setVersion((value) => value + 1)
    }).catch(() => setToastText('Unable to load admin data.'))
  }, [])
  const toast = (text) => { setToastText(text); window.setTimeout(() => setToastText(''), 2600) }
  const handleBookingUpdated = (booking) => {
    const index = adminBookings.findIndex((item) => item.id === booking._id)
    if (index >= 0) { adminBookings[index] = { ...adminBookings[index], status: booking.status.replace('_', ' ') }; setVersion((value) => value + 1) }
  }
  return <div className="admin-shell"><Sidebar open={open} onClose={() => setOpen(false)} /><div className="admin-main"><Header onMenu={() => setOpen(true)} /><Routes><Route path="/admin" element={<Dashboard viewBooking={setSelected} toast={toast} />} /><Route path="/admin/bookings" element={<BookingsPage viewBooking={setSelected} />} /><Route path="/admin/bookings/:bookingId" element={<AdminBookingDetailsRoute toast={toast} />} /><Route path="/admin/services" element={<ServicesPage toast={toast} />} /><Route path="/admin/customers" element={<CustomersPage toast={toast} />} /><Route path="/admin/notifications" element={<NotificationsPage toast={toast} />} /><Route path="/admin/reviews" element={<ReviewsPage />} /><Route path="/admin/settings" element={<SettingsPage />} /><Route path="*" element={<Navigate to="/admin" replace />} /></Routes></div>{selected && <BookingUpdateModal booking={selected} onClose={() => setSelected(null)} onUpdated={handleBookingUpdated} toast={toast} />}{toastText && <Toast text={toastText} close={() => setToastText('')} />}</div>
}
