import { Link, useNavigate, useParams } from 'react-router-dom'
import { useEffect, useState } from 'react'
import { cancelBooking, getBooking } from '../services/api'

const formatDate = (value) => value ? new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : 'Pending'
const labels = { pending: 'Pending', confirmed: 'Confirmed', scheduled: 'Scheduled', in_progress: 'In progress', completed: 'Completed', cancelled: 'Cancelled', overdue: 'Overdue' }

export default function BookingDetails() {
  const { bookingId } = useParams(); const navigate = useNavigate(); const [booking, setBooking] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [updating, setUpdating] = useState(false)
  useEffect(() => { getBooking(bookingId).then((response) => setBooking(response.booking)).catch(() => setError('We could not load this booking right now.')).finally(() => setLoading(false)) }, [bookingId])
  const cancel = async () => { if (!window.confirm('Are you sure you want to cancel this booking?')) return; setUpdating(true); try { const response = await cancelBooking(bookingId); setBooking(response.booking) } catch (requestError) { setError(requestError.response?.data?.message || 'This booking could not be cancelled.') } finally { setUpdating(false) } }
  if (loading) return <section className="booking-details-page"><p className="loading-message">Loading booking...</p></section>
  if (error || !booking) return <section className="booking-details-page"><p className="form-error" role="alert">{error || 'Booking not found.'}</p><Link className="primary-button" to="/bookings">My bookings</Link></section>
  return <section className="booking-details-page"><header className="page-heading"><button type="button" onClick={() => navigate(-1)} aria-label="Go back"><i className="ri-arrow-left-line" /></button><h1>Booking details</h1></header><div className="booking-detail-content"><div className="detail-status"><span className={`status-badge status-${booking.status}`}>{labels[booking.status] || booking.status}</span><small>Booking ID: {booking._id}</small></div><article className="detail-block"><h2>Service</h2><b>{booking.serviceName}</b><p>{booking.serviceDescription}</p></article><article className="detail-block"><h2>Customer</h2><p>{booking.customer.name}<br />{booking.customer.phone}{booking.customer.email && <><br />{booking.customer.email}</>}</p></article><article className="detail-block"><h2>Location</h2><p>{booking.location.address}</p><a className="location-link" href={`https://www.google.com/maps/search/?api=1&query=${booking.location.latitude || ''},${booking.location.longitude || ''}`} target="_blank" rel="noreferrer">Open in maps</a></article><article className="detail-block"><h2>Expected by</h2><b>{formatDate(booking.serviceDeadlineAt)}</b></article>{booking.instructions && <article className="detail-block"><h2>Instructions</h2><p>{booking.instructions}</p></article>}<article className="detail-block"><h2>Timeline</h2><ol className="booking-timeline">{(booking.statusHistory || []).map((event) => <li className="complete" key={`${event.status}-${event.at}`}><span>✓</span>{labels[event.status] || event.status}<small>{formatDate(event.at)}</small></li>)}</ol></article>{!['completed', 'cancelled'].includes(booking.status) && <button className="cancel-booking" type="button" disabled={updating} onClick={cancel}>{updating ? 'Updating booking...' : 'Cancel booking'}</button>}<Link className="secondary-link" to="/bookings">Back to my bookings</Link></div></section>
}
