const Booking = require('../models/Booking');
const User = require('../models/User');
const Service = require('../models/Service');
const Notification = require('../models/Notification');

exports.dashboard = async (req, res, next) => { try { const [bookingCounts, totalCustomers, totalServices, activeServices, unreadNotifications, recentBookings, recentNotifications] = await Promise.all([Booking.aggregate([{ $group: { _id: '$status', count: { $sum: 1 } } }]), User.countDocuments({ role: 'customer' }), Service.countDocuments(), Service.countDocuments({ isActive: true }), Notification.countDocuments({ recipient: req.user.userId, isRead: false }), Booking.find().sort({ createdAt: -1 }).limit(8).populate('customer', 'name phone').populate('service', 'name'), Notification.find({ recipient: req.user.userId }).sort({ createdAt: -1 }).limit(8).populate({ path: 'booking', populate: [{ path: 'customer', select: 'name phone' }, { path: 'service', select: 'name' }] })]); const counts = Object.fromEntries(bookingCounts.map(({ _id, count }) => [_id, count])); res.json({ success: true, data: { stats: { totalBookings: bookingCounts.reduce((sum, item) => sum + item.count, 0), pendingBookings: counts.pending || 0, confirmedBookings: counts.confirmed || 0, inProgressBookings: counts.in_progress || 0, completedBookings: counts.completed || 0, cancelledBookings: counts.cancelled || 0, totalCustomers, totalServices, activeServices, unreadNotifications }, recentBookings, recentNotifications } }); } catch (error) { next(error); } };
exports.notifications = async (req, res, next) => { try { res.json({ success: true, data: { notifications: await Notification.find({ recipient: req.user.userId }).sort({ createdAt: -1 }).populate('booking') } }); } catch (error) { next(error); } };
exports.readNotification = async (req, res, next) => { try { const notification = await Notification.findOneAndUpdate({ _id: req.params.id, recipient: req.user.userId }, { isRead: true }, { new: true }); if (!notification) return res.status(404).json({ success: false, message: 'Notification not found' }); res.json({ success: true, data: { notification } }); } catch (error) { next(error); } };
exports.readAll = async (req, res, next) => { try { await Notification.updateMany({ recipient: req.user.userId, isRead: false }, { isRead: true }); res.json({ success: true }); } catch (error) { next(error); } };
